### ISSUE TITLE
Check if input string contains text from an array of substrings -- Chatbot

### ISSUE THREAD

**Issue by doghousetv** [GeorgeArubi/Playlist-Chatbot#1]
I'm trying to write a function that checks if  the input string "lowerCaseMessage" contains any text from an array of substrings, i.e. ["hello", "hey", "hi"]. Which will trigger the greet() function -- thank you in advance!

parse(message) {
      const lowerCaseMessage = message.toLowerCase()

      if (lowerCaseMessage.includes("hello")){
          this.actionProvider.greet()
      }

      if (lowerCaseMessage.includes("hey")){
        this.actionProvider.greet()
      }

     if (lowerCaseMessage.includes("hi")){
        this.actionProvider.greet()
      }
}

**Comment by Noamrok** [comment]
Hi,

If you are doing the same action on each of the elements in the substrings array you can (and should) use a for loop.

```
function parse(message)
{
     const lowerCaseMessage = message.toLowerCase();
     var substrings = ["hello", "hey", "hi"];
     for (var i = 0 ; i < substrings.length ; i++) 
          if (lowerCaseMessage.includes(substrings[i]))
               this.actionProvider.greet();
}
```

Hope it helps!

**Comment by doghousetv** [comment]
Thank you, really helped me out here!!
